### PR TITLE
feat(icons): SpaceAndComponent

### PR DESCRIPTION
**Pull request by romiekos**
image

### CODE REVIEW

**Review by bnjm — APPROVED** [review]

**Comment by ianaa** [comment]
@michalarchilogic can you add this icon to honeycomb file in figma? And @romandkos I think we need a better name for it

**Comment by romiekos** [comment]
> And @romandkos I think we need a better name for it

@ianaa Do you have an idea how to name it? ResourceMultiselection? MultipleComponents?

**Comment by ianaa** [comment]
I think `SpaceAndComponent` (since those are the names of the separate icons used here) or `CombinedResources`. 
@michalarchilogic do you have an idea?

**Comment by michalarchilogic** [comment]
@romandkos @ianaa Here you go: https://www.figma.com/file/rsElRZClpRdcKlakIrlwOP/Honeycomb-2.0?type=design&node-id=7080-21109&mode=design&t=vpXGEUjFn6Q55z8K-4

I named it SpaceAndComponent.

**Comment by romiekos** [comment]
> I named it SpaceAndComponent.

https://github.com/archilogic-com/honeycomb/pull/217/commits/1abb5c1664345e047e52e727600f48be9ff5b094

**Review by luk-zap — APPROVED** [review]

**Pull request merged**
